FROM pipdevs/node:8.4.0-python

# set working directory
WORKDIR /app

# Instal dependencies
RUN npm -g config set user root \
    && npm install -g protoc@1.0.4 \
    && npm install ts-protoc-gen@^0.9.0

# Copy the entire project
COPY . .

# Generate proto files
RUN cd src/protos && protoc --plugin=protoc-gen-ts=../../node_modules/.bin/protoc-gen-ts --js_out=import_style=commonjs,binary:./ --ts_out=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` component_v1.proto
