version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    command: ${TEST_CMD:-npm run delay_test}
    links:
      - mongo
      - postgres
      # - sqlserver
    environment:
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=test
      - POSTGRES_SERVICE_HOST=postgres
      - POSTGRES_SERVICE_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
      # - SQLSERVER_SERVICE_HOST=sqlserver
      # - SQLSERVER_SERVICE_PORT=1433
      # - SQLSERVER_USER=sa
      # - SQLSERVER_PASS=Sqlserver_123
      # - SQLSERVER_DB=master

  mongo:
    image: mongo:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  # sqlserver:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: sqlserver
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: Sqlserver_123
  