version: '3.3'

services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432" 

  sqlserver:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: sqlserver
      environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: Sqlserver_123
      ports:
        - "1433:1433"
    